---
apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-resource-constraint
spec:
  limits:
  - default:
     cpu: 500m
    defaultRequest:
     cpu: 500m
    max:
     cpu: "1"
    min:
     cpu:100m
    type: Container

  - type: "Pod"
    max:
      cpu: "1"
      memory: "1Gi"
    min:
      cpu: "200m"
      memory: "6Mi"
    maxLimitRequestRatio:
      cpu: "10"
---
apiVersion: v1
kind: Pod
metadata:
  name: stress
spec:
  containers:
  - image: balatuluva/stress
    imagePullPolicy: Always
    name: stress
    command: ["sleep","200"]
    